# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  image-build:
    environment:
      DOCKER_IMAGE: theoldmoon0602/shellgeibot
    docker:
      - image: docker:stable
        environment:
          DOCKER_BUILDKIT: "1"  # Enable Docker BuildKit
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true  # BuildKit の DLC はまだ効かないっぽい
          version: "18.09.3"
      - run:
          name: Build Docker image
          command: docker build -t ${DOCKER_IMAGE} --progress=plain .
      - run:
          name: Test Docker image
          command: DOCKER_IMAGE=${DOCKER_IMAGE} bats docker_image.bats
      - run:
          name: Login Docker Hub
          command: echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push ${DOCKER_IMAGE}:${CIRCLE_BRANCH}
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              DATE_TAG=$(date +%Y%m%d)
              docker tag ${DOCKER_IMAGE}:${CIRCLE_BRANCH} ${DOCKER_IMAGE}:${DATE_TAG}
              docker push ${DOCKER_IMAGE}:${DATE_TAG}
            else
              docker push ${DOCKER_IMAGE}:${CIRCLE_BRANCH}
            fi
      - run:
          name: Apply New Image to Running
          command: |
            test "${CIRCLE_BRANCH}" = master && ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "docker pull theoldmoon0602/shellgeibot:master && docker rmi $(docker images | grep '<none>' | awk '{print $3}')"

workflows:
  version: 2
  commit-workflow:
    jobs:
      - image-build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - image-build
